version: '3.3'
services:
  brickscraper:
    image: snakehead007/brickscraper
    deploy:
      replicas: 1
  match:
    image: dsys/match:latest
    ports:
    - 8888:8888
    command: ["/wait-for-it.sh", "-t", "60", "elasticsearch:9200", "--", "gunicorn", "-b", "0.0.0.0:8888", "-w", "4", "server:app"]
    deploy:
      replicas: 4
  elasticsearch:
    image: elasticsearch:6.4.2
    ports:
    - 9200:9200
    deploy:
      replicas: 4
  rembg:
    image: snakehead007/rembg-docker:latest
    ports:
    - 5000:5000
    deploy:
      replicas: 4
networks:
  default:
